version: '3.7'
services:
  api:
    image: docker.pkg.github.com/equinor/witsml-explorer/witsmlexplorer-api:latest
    container_name: witsmlexplorer-api
    volumes:
      - ../../config.json:/app/config.json:ro #May be changed

  web:
    image: docker.pkg.github.com/equinor/witsml-explorer/witsmlexplorer-frontend:latest
    container_name: witsmlexplorer-frontend

  nginx:
    image: nginx
    container_name: witsmlexplorer-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/nginx:/etc/nginx     #May be changed
      - /data/logs:/var/log/nginx  #May be changed
    depends_on:
      - web
      - api
