name: Build and Test
on:
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Build with dotnet
        run: dotnet build /warnaserror --configuration Release
      - name: Test with dotnet
        run: dotnet test ./Tests/WitsmlExplorer.Api.Tests/WitsmlExplorer.Api.Tests.csproj --configuration Release

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: yarn
        working-directory: ./Src/WitsmlExplorer.Frontend
      - name: Linting
        run: yarn lint
        working-directory: ./Src/WitsmlExplorer.Frontend
      - name: Prettier
        run: npx prettier --check .
      - name: Build
        run: yarn build
        working-directory: ./Src/WitsmlExplorer.Frontend
      - name: Test
        run: yarn test
        working-directory: ./Src/WitsmlExplorer.Frontend
