name: Merge upstream main
on:
  schedule:
    - cron:  '0 06,12 * * *'
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Merge upstream
        run: |
          git pull --unshallow

          git remote add upstream https://github.com/equinor/witsml-explorer.git
          git fetch upstream main

          git checkout main
          git merge --no-edit upstream/main
          git push origin main
