name: Package and publish

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/publish.yml'
      - 'Src/Witsml/**'

jobs:
  build:
    name: Package and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          source-url: https://nuget.pkg.github.com/equinor/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Install dependencies
        run: dotnet restore
      - name: Build with dotnet
        run: dotnet build /warnaserror --configuration Release --no-restore
      - name: Test with dotnet
        run: dotnet test ./Tests/WitsmlExplorer.Api.Tests/WitsmlExplorer.Api.Tests.csproj --configuration Release --no-restore
      - name: Package
        run: dotnet pack --configuration Release Src/Witsml -p:Version=2.0.${GITHUB_RUN_NUMBER}
      - name: Publish
        run: dotnet nuget push --api-key ${{secrets.NUGET_PUBLISH_KEY}} --source https://api.nuget.org/v3/index.json Src/Witsml/bin/Release/WitsmlClient.2.0.${GITHUB_RUN_NUMBER}.nupkg
